"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import NavigationBar from "@/components/navbar";
import { StripeProvider } from "@/components/stripeContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StripeProvider>
          <NavigationBar />
          {children}
        </StripeProvider>
      </body>
    </html>
  );
}
